name: todo_list
description: A simple todo application
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.5
  flutter_form_bloc: ^0.19.0
  meta: ^1.1.8
  uuid: ^2.2.2
  shared_preferences: ^0.5.10
  provider: ^4.3.2+2
  ff_navigation_bar: ^0.1.5
  calendar_strip: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
